# Generated by Django 3.1.7 on 2021-05-22 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('img', models.ImageField(default='enviro.png', upload_to='')),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True, default='Save Earth!')),
                ('country', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_recycle', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0)),
                ('user_recycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trash.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Reduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_reduce', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0)),
                ('user_reduce', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trash.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Reuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_reuse', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0)),
                ('user_reuse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trash.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300)),
                ('recycle_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trash.recycle')),
                ('reduce_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trash.reduce')),
                ('reuse_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trash.reuse')),
            ],
        ),
        migrations.CreateModel(
            name='PointWorth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trash.profile')),
            ],
        ),
    ]
